import './App.css';
import React, { useState } from "react";
// RobotSimulator component from the file ./RobotSimulator.js. This component likely contains the logic for simulating the behavior of a robot.
import RobotSimulator from "./RobotSimulator"; 
import RobotCommand from './components/RobotCommand';

const App = () => {
  const [commands, setCommands] = useState("");

  // report, which will store the report generated by executing the commands. setReport is a function used to update the report state.
  const [report, setReport] = useState("");
  // RobotSimulator class, presumably used for simulating the behavior of a robot..
  const simulator = new RobotSimulator();

  const handleInputChange = (event) => {
    setCommands(event.target.value);
  };

  const executeCommands = () => {

    const commandsArray = commands.toUpperCase().split("\n");
    commandsArray.forEach((command) => {
      if (command.startsWith("PLACE")) {
        const [, position] = command.split(" ");
        const [x, y, f] = position.split(",");
        simulator.place(parseInt(x), parseInt(y), f);
      } else if (command === "MOVE") {
        simulator.move();
      } else if (command === "LEFT") {
        simulator.left();
      } else if (command === "RIGHT") {
        simulator.right();
      } else if (command === "REPORT") {
        setReport(simulator.report());
      }
    });

  };

  return (
    <div className="App">
      <h1>Toy Robot Simulator</h1>
      <h3><span className='btn_color'>Note :</span> Put the value under text area and click on Execute Button blink button </h3>
      <textarea className="textarea"
      value={commands}
       onChange={handleInputChange} 
       /><br/><br/><br/>
      <button className="neon-button"
      onClick={executeCommands}
      >Execute</button><br/><br/>
      <h2>Report:</h2>
      <p>{report}</p><br/><br/>
      <RobotCommand/>
    </div>
  );
};

export default App;
